- README.md
> Vaibhavantil1 patch 1

- install.sh
Handle multiple cases:
1. Add pre-flight checks for docker permissions
2. Add $PATH on multiple profiles
3. Add cleanup
4. Support global installations with `sudo`
> Feature: Update Installer

- config/semantics/java.yaml
add - semantic support
fix - https://github.com/Privado-Inc/privado-core/pull/111
> add - semantic support

- docs/getting-started-with-privado/README.md
Since Docker is needed to successfully use the Quickstart steps, I added it to README.md
> Docker is needed to run Privado, added to readme

- README.md
Clarify language support and move it up higher in the readme.
> make language support more visible in readme

- config/semantics/java.yaml
- rules/sinks/storages/cookiemanager/java.yaml
- rules/sinks/storages/facebooklocalcache/java.yaml
- rules/sinks/storages/sharedpreferences/java.yaml
- rules/sources/financial_data.yaml
- rules/sources/online_identifiers.yaml
- rules/sources/personal_identification.yaml
**Sources**
- Update age source regex rule to avoid FPs
- Cookies can be called tokens
- PaymentNonce can be a separate rule
**Sink**
- Facebook can use local cache and local storage to keep tokens/cookies
- CookieManager is used to locally save cookies in Android
**Semantics**
- Return values of getNonce, Split and Replace methods must be tainted
> Update - filters sources/sinks/semantics

- .github/workflows/comparison-result.yml
JIRA Ticket: https://privado-ai.atlassian.net/browse/LE-166
> Github workflow for comparison added

- rules/sinks/storages/jdbc/java.yaml
https://www.javatpoint.com/spring-NamedParameterJdbcTemplate-example
> Update JDBC rule to support namedJdbcTemplate

- rules/sinks/third_parties/api/javascript.yaml
<Script
id="yieldbird-script"
data-testid="yieldbird-script"
src="//jscdn.yieldbird.com/d67edacf-d1f9-4edd-a8ea-a94a7f86c921/yb.js"
strategy="lazyOnload"
/>
> Handling to detect urls without protocol

- config/systemConfig/java.yaml
> SOAP rules

- README.md
- config/sinkSkipList/python.yaml
- config/systemConfig/python.yaml
- rules/sinks/storages/amazonS3/python.yaml
- rules/sinks/third_parties/sdk/amplitude/java.yaml
- rules/sinks/third_parties/sdk/facebook/java.yaml
* Python GA support
* fix: more sdks for facebook
* Amplitude android sdk
---------
> Rules/third party java (#223)

- config/audit/collections/java.yaml
- config/audit/utility/java.yaml
- config/audit/webClient/java.yaml
Added Basic Audit Collections, Webclient, and Utility Rules.
> Added Basic Audit Rules

- config/audit/collections/java.yaml
- config/audit/utility/java.yaml
- config/audit/webClient/java.yaml
* Added Basic Audit Rules
* Added more utility dependency
> Release 15th May 2023: Added Basic Audit Rules 

- config/audit/utility/java.yaml
> Audit Utility rule fixed

- config/audit/utility/java.yaml
Fixed the Utility rule that earlier throwing warning.
> Release 17th May 2023: Audit utility rule fixed 

- .github/workflows/comparison-result.yml
Passing base and head branch repo url info to comparison script.
> Added external PR support

- rules/sinks/storages/cookiemanager/javascript.yaml
- rules/sinks/storages/indexedDB/javascript.yaml
- rules/sources/usage_data.yaml
* add datadog initialization params which default track click behaviour
* Add IndexedDB storage rule
---------
> Sources/click stream ddhq (#284)

- rules/sinks/storages/redis/go.yaml
changed redis rules for golang
> Golang redis rules

- rules/sinks/storages/arangodb/go.yaml
- rules/sinks/storages/bigtable/go.yaml
- rules/sinks/storages/cassandra/go.yaml
- rules/sinks/storages/cognito/go.yaml
- rules/sinks/storages/cosmosdb/go.yaml
- rules/sinks/storages/dynamodb/go.yaml
- rules/sinks/storages/elasticsearch/go.yaml
- rules/sinks/storages/kinesis/go.yaml
- rules/sinks/storages/mongodb/go.yaml
> Golang storage rules

- .github/workflows/comparison-result.yml
@pandurangpatil , please review.
> Fix: Change slack action to upload file

- config/exclusions/go.yaml
This reverts commit 69b9f9b8a90d55caedee78f222f245c0fb4ac291.
> Revert "go exclusion rule fix (#354)"

- rules/collections/android/any.yaml
Add special collection rules for android tagger for android layout XML based tagging
> Add android collection rules

- rules/sinks/third_parties/sdk/datadoghq/java.yaml
source : https://docs.datadoghq.com/developers/community/libraries/
> add datadog java sdks

- rules/collections/android/any.yaml
* add tags to link source to collections
Required for: https://github.com/Privado-Inc/privado-core/pull/862
* remove rule
---------
> add tags to link source to collections (#367)

- rules/sinks/third_parties/sdk/facebook/javascript.yaml
- rules/sinks/third_parties/sdk/google/javascript.yaml
- rules/sinks/third_parties/sdk/pinterest/javascript.yaml
- rules/sinks/third_parties/sdk/tiktok/javascript.yaml
Ref: https://github.com/Privado-Inc/privado-core/pull/945
> Pixel tracking APIs

- config/systemConfig/kotlin.yaml
Jira Issue - https://privado-ai.atlassian.net/browse/CA-196
> CA-196 | Add Ktor httpclient in possible clients list

- rules/collections/annotations/java.yaml
Add missing JAX-RS collection annotations.
> CA-205 | Add JAX-RS collection annotations for Java

- rules/sinks/storages/mongodb/java.yaml
Update existing MongoDB morphia rules with missing matches.
> CA-206 | Update morphia mongodb storage sink rules for Java and Kotlin

- rules/sinks/leakages/logs/go.yaml
Print/Printf logs to console
SPrint/SPrintf returns a formatted string
FPrint/FPrintf writes to a file
> fix : https://github.com/Privado-Inc/privado/pull/400

- rules/sinks/storages/cookiemanager/javascript.yaml
prevent matching cookieSettings
> cookie write rule

- rules/sinks/storages/kinesis/go.yaml
- rules/sinks/storages/kinesis/java.yaml
- rules/sinks/storages/kinesis/javascript.yaml
- rules/sinks/storages/kinesis/python.yaml
- rules/sinks/third_parties/sdk/amazon/javascript.yaml
- rules/sinks/third_parties/sdk/amazon/python.yaml
- rules/sinks/third_parties/sdk/amazonaws/java.yaml
Jira issue - https://privado-ai.atlassian.net/browse/CA-203
> CA-203 | Fix AWS Kinesis naming, making it uniform

- config/systemConfig/default.yaml
* Added repo config metadata rules
* system config rule change
> Repo Config Metadata Rules (#423)

- rules/collections/annotations/csharp.yaml
This goes alongside https://github.com/Privado-Inc/privado-core/pull/1032
> csharp: annotation based collections rule

- config/systemConfig/default.yaml
* added code line limit
* Limit name change
> Release PR

- config/systemConfig/csharp.yaml
- rules/sinks/internal_apis/api/csharp.yaml
- rules/sinks/third_parties/api/csharp.yaml
- rules/sinks/third_parties/api/go.yaml
- rules/sinks/third_parties/api/java.yaml
- rules/sinks/third_parties/api/php.yaml
- rules/sinks/third_parties/api/python.yaml
- rules/sinks/third_parties/api/ruby.yaml
- For csharp, added rules to support API detection
- For other language, changed regex to not identify gmail as api sink
> API detection fix

- .github/workflows/comparison-result.yml
Installing sbt causes a problem with latest ubuntu. Using 22.04 solves the problem.
> Change OS version of runner

- rules/sinks/third_parties/sdk/chatwork/ruby.yaml
> fix - chatwork rule in ruby

- rules/sinks/third_parties/sdk/twitter/java.yaml
https://github.com/xdevplatform/twitter-api-java-sdk
> official java sdk for twitter api
